# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creators',
            new_name='Creator',
        ),
        migrations.RenameModel(
            old_name='Workers',
            new_name='Worker',
        ),
    ]
