# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 18:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests', '0003_auto_20170320_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='queue',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='worker',
        ),
        migrations.AddField(
            model_name='queue',
            name='creators',
            field=models.ManyToManyField(related_name='create_queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queue',
            name='workers',
            field=models.ManyToManyField(related_name='work_queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Creator',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
    ]
