# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20170324_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='queue',
            name='email_box_host',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='email_box_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='email_box_port',
            field=models.IntegerField(default=995),
        ),
        migrations.AddField(
            model_name='queue',
            name='email_box_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='email_box_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('O', 'Open'), ('A', 'Assigned'), ('C', 'Closed')], max_length=1),
        ),
        migrations.AlterField(
            model_name='update',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='requests.Ticket'),
        ),
    ]
