# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_auto_20170325_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='email_box_host',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_password',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_port',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_type',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='email_box_user',
        ),
        migrations.AddField(
            model_name='queue',
            name='mailbox',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
